### ISSUE TITLE
f13-f24 keys

### ISSUE THREAD

**Issue by scott-gr** [vika-sonne/special-purposes-keyboard#1]
I'm glad I saw your review on the product page! The CLI works well and the instructions are clear.

I suggest adding more fn row keys to avoid conflict with standard keyboard. This worked for me:

```  'f13': 0x68,
  'f14': 0x69,
  'f15': 0x6A,
  'f16': 0x6B,
  'f17': 0x6C,
  'f18': 0x6D,
  'f19': 0x6E,
  'f20': 0x6F,
  'f21': 0x70,
  'f22': 0x71,
  'f23': 0x72,
  'f24': 0x73,
  ```
  
  More here http://www.quadibloc.com/comp/scan.htm

**Comment by vika-sonne** [comment]
Thanks for Your attention to this little code composing !
I am happy that my work a bit useful.
Now Your suggestions included into code.
